apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template: # inside here is like a blueprint for pods creations
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
          - containerPort: 27017
        env: # get these details from DockerHub about how to use mongo container
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  # selector key/value here is very important. Selectors and Labels is a way Resources interconnect each other
  selector:
    # this key/value points to the same label key/value in the Deployment so to find the resources (Pods) to attach to
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017         # exposed Service port
      targetPort: 27017   # Container port > must match the one in the Deployment template
